# Generated by Django 5.0.2 on 2024-02-14 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField()),
                ('description', models.TextField(blank=True, null=True)),
                ('publication_date', models.DateField()),
                ('publication', models.TextField()),
                ('doi', models.TextField(blank=True, null=True)),
                ('citation', models.FloatField(blank=True, null=True)),
                ('impact_factor', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('profile', models.URLField(blank=True, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='papers.paper')),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
    ]
