# Generated by Django 5.0.2 on 2024-02-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_alter_author_author_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_type',
            field=models.CharField(choices=[('FIRST', 'First Author'), ('CO', 'Co-Author')], default='CO', max_length=9),
        ),
    ]
