# Generated by Django 5.0.2 on 2024-02-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_alter_author_author_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='paper',
        ),
        migrations.AddField(
            model_name='paper',
            name='authors',
            field=models.ManyToManyField(to='papers.author'),
        ),
    ]
