# Generated by Django 5.0.2 on 2024-02-22 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0006_remove_paper_authors_author_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.paper'),
        ),
    ]
