# Generated by Django 5.0.2 on 2024-02-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0007_alter_author_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='doi',
            field=models.URLField(blank=True, null=True),
        ),
    ]
