# Generated by Django 5.0.2 on 2024-02-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='department',
        ),
        migrations.RemoveField(
            model_name='customusers',
            name='group',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
